---
title: "U.S. Military presence i Greenland"
author: "August Dam Harden and Ellis-Tex Bastian Binderup"
date: "2026-05-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## R Markdown

```{r}
### Mapping the US military presence in Greenland during the 20th century.

# To install the package for this script, we run these commands:
# install.packages("leaflet")
# install.packages("htmltools")
# gs4_deauth()  # Giving the script access to our Google Sheets file


# Activating the library
library(leaflet)
library(htmltools)
library(tidyverse)
library(googlesheets4)
library(dplyr)


# Reading the data:
places <- read_sheet("https://docs.google.com/spreadsheets/d/1hX2x3Zs2SMS3P6nGJ93EBRsbVprymsW25ZdIE7pYAs4/edit?gid=0#gid=0",
        col_types = "cccnnccc",  
        range = "Greenland")
  
# The function to convert Decimal Degrees to DMS string:
  dd_to_dms <- function(dd, is_lat = TRUE) {
    if (is_lat) { dir <- ifelse(dd >= 0, "N", "S") } 
    else { dir <- ifelse(dd >= 0, "E", "W") }
    abs_dd <- abs(dd)
    degrees <- floor(abs_dd)
    minutes_raw <- (abs_dd - degrees) * 60
    minutes <- floor(minutes_raw)
    seconds <- round((minutes_raw - minutes) * 60, 1)
    paste0(degrees, "° ", minutes, "' ", seconds, '\" ', dir)
  }
  
# Processing the data:
  places_with_dms <- places %>%
    mutate(
      Lat_DMS = dd_to_dms(Latitude, is_lat = TRUE),
      Lng_DMS = dd_to_dms(Longitude, is_lat = FALSE)
    )
  
# Special icons and colours based on the type of "Facility":
  places_with_icons <- places_with_dms %>%
    mutate(
      icon_name = case_when(
        Facility == "Airbase"                   ~ "plane",
        Facility == "Weather station"           ~ "ion-umbrella",      
        Facility == "Weather & radio station"   ~ "ion-radio-waves",     
        Facility == "Marine station"            ~ "ion-flag",     
        Facility == "Radar station"             ~ "ion-wifi",       
        Facility == "LORAN station"             ~ "ion-navigate",           
        Facility == "Radio finding station"     ~ "compass",
        Facility == "Military research station" ~ "ion-ios-search",
        Facility == "Radar station (for Thule)" ~ "ion-eye",
        TRUE                                    ~ "help-circle" 
      ),
      icon_colour = case_when(
        Facility == "Airbase"                   ~ "blue",
        Facility == "Weather station"           ~ "orange",
        Facility == "Weather & radio station"   ~ "green",
        Facility == "Radar station"             ~ "red",
        Facility == "Marine station"            ~ "purple",
        Facility == "LORAN station"             ~ "lightgray",
        Facility == "Radio finding station"     ~ "beige",
        Facility == "Military research station" ~ "lightblue",
        Facility == "Radar station (for Thule)" ~ "cadetblue",
        TRUE                                    ~ "gray"
      )
    )
  
  map_icons <- awesomeIcons(
    icon = places_with_icons$icon_name,
    iconColor = "white",
    markerColor = places_with_icons$icon_colour,
    library = "ion" 
  )
  
# The icons are built on the basis of the coloumns just made.
  map_icons <- awesomeIcons(
    icon = places_with_icons$icon_name,
    iconColor = "white",
    markerColor = places_with_icons$icon_colour,
    library = "ion" # The Ionicon-library contains modern and clean icons.
  )
  
# This code generates the map:
  leaflet(data = places_with_icons) %>%    
    addProviderTiles(providers$Esri.WorldImagery, group = "Aerial") %>%
    addProviderTiles(providers$OpenTopoMap, group = "Topography") %>%
    
    setView(lng = -44.25, lat = 75.60, zoom = 4) %>%
    
# The function addAwesomeMarkers is used and the 'map_icons' are attached.
    addAwesomeMarkers(
      lng = ~Longitude,
      lat = ~Latitude,
      icon = map_icons,
      popup = ~paste(
        "<b>", `Military installation`, "</b><br>", 
        "<b>Type:</b> ", Facility, "<br>", 
        Description, "<br>", 
        "<b>Operational:</b> ", `Operational`, "<br>",
        "<b>Coordinates:</b> ", Lat_DMS, ", ", Lng_DMS
      ) 
    ) %>%

# adding the option to display both Aerial and topography.
    addLayersControl(
      baseGroups = c("Aerial", "Topography"),
      options = layersControlOptions(collapsed = FALSE)
    )
  
  
```

